services:
  mongodb:
    image: mongo:8.2-noble
    container_name: mongodb
    restart: "no"
    env_file:
      - ./mongodb.env
      - ./mongodb.env.local
    networks:
      - database
    ports:
      - 127.0.0.1:27017:27017
    volumes:
      - ${DATA_DIR}/mongo:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--quiet", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    deploy:
      resources:
        limits:
          memory: ${MEM_LIMIT}

networks:
  database:
    external: true
