services:
  chat-api:
    container_name: chat-api
    image: ghcr.io/danny-avila/librechat-dev:latest
    restart: on-failure:3
    user: ${UID}:${GID}
    userns_mode: host
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - mongodb
      - rag-api
    networks:
      - genai
      - proxy
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - .env
      - .env.local
    environment:
      - HOST=0.0.0.0
      - MONGO_URI=${MONGO_URI}
      - MEILI_HOST=http://meilisearch:7700
      - RAG_PORT=${RAG_PORT:-8000}
      - RAG_API_URL=http://rag-api:${RAG_PORT:-8000}
    volumes:
      - ${PROJ_DIR}/.env:/app/.env
      - ${DATA_DIR}/config.yaml:/app/librechat.yaml
      - ${DATA_DIR}/images:/app/client/public/images
      - ${DATA_DIR}/uploads:/app/uploads
      - ${DATA_DIR}/logs:/app/logs
    labels:
      # Traefik integration
      - "traefik.enable=true"
      - "traefik.http.routers.open-webui.entrypoints=websecure"
      - "traefik.http.routers.open-webui.rule=Host(`chat.${TRAEFIK_ACME_DOMAIN}`)"
      - "traefik.http.routers.open-webui.tls.certresolver=cloudflare"
      - "traefik.http.services.open-webui.loadbalancer.server.port=3080"
      # Homepage integration
      - "homepage.group=Artificial Intelligence"
      - "homepage.name=LibreChat"
      - "homepage.icon=librechat.svg"
      - "homepage.href=https://chat.${TRAEFIK_ACME_DOMAIN}"
