services:
  mariadb:
    image: mariadb:11.8
    container_name: mariadb
    restart: "no"
    env_file:
      - ./mariadb.env
    environment:
      MARIADB_AUTO_UPGRADE: "1"
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    command:
      - --innodb-buffer-pool-size=1G
      - --innodb-log-file-size=256M
      - --innodb-io-capacity=200
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    networks:
      - database
    ports:
      - 127.0.0.1:3306:3306
    secrets:
      - db_password
      - db_root_password
    volumes:
      - ${DATA_DIR}/mariadb:/var/lib/mysql
    deploy:
      resources:
        limits:
          memory: 2GB

networks:
  database:
    external: true

secrets:
  db_password:
    file: ${DATA_DIR}/mariadb_password.txt
  db_root_password:
    file: ${DATA_DIR}/mariadb_root_password.txt
