services:
  forge-neo:
    build: .
    image: ghcr.io/delfianto/compose/forge-neo:latest
    container_name: forge-neo
    restart: "no"
    networks:
      - proxy
    environment:
      - UV_CACHE_DIR=/app/uv_cache
    command: >
      --enable-insecure-extension-access
      --cuda-malloc
      --listen
      --port 7860
      --theme dark
      --forge-ref-comfy-home /comfyui
    volumes:
      - ${DATA_DIR}:/comfyui
      - ${EXEC_DIR}/venv:/app/venv
      - ${EXEC_DIR}/uv_cache:/app/uv_cache
      - ${HOME}/Pictures/StableDiffusion:/app/output
    devices:
      - nvidia.com/gpu=0
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.forge.entrypoints=websecure"
      - "traefik.http.routers.forge.rule=Host(`forge.${TRAEFIK_ACME_DOMAIN}`)"
      - "traefik.http.routers.forge.tls.certresolver=cloudflare"
      - "traefik.http.services.forge.loadbalancer.server.port=7860"
      - "homepage.group=Artificial Intelligence"
      - "homepage.name=Forge Neo"
      - "homepage.icon=/icons/stablediff.png"
      - "homepage.href=https://forge.${TRAEFIK_ACME_DOMAIN}"

networks:
  proxy:
    external: true
