[ai-bifrost]
requires = ["db-vchord", "db-valkey"]

[ai-librechat]
requires = ["db-vchord", "ai-bifrost", "ai-embedding"]
wants = ["ai-ollama"]

[ai-openwebui]
requires = ["db-vchord", "ai-bifrost", "ai-embedding"]
wants = ["ai-ollama"]

[infra-forgejo]
requires = ["db-vchord"]

[media-immich]
requires = ["db-vchord", "db-valkey"]
