services:
  # Embedding Service
  infinity-embed:
    image: michaelf34/infinity:latest
    container_name: infinity-embed
    restart: always
    networks:
      - proxy
      - llm
    environment:
      - DATA_DIR=${DATA_DIR}
      - NVIDIA_VISIBLE_DEVICES=${EMBEDDER_GPU}
      - INFINITY_MODEL_ID=${RAG_EMBED_MODEL}
      - INFINITY_LOG_LEVEL=info
    volumes:
      - ${DATA_DIR}/infinity:/app/.cache
    command: >
      v2
      --device cuda
      --engine torch
      --host 0.0.0.0
      --port 7990
      --url-prefix /v1
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  # Rerankig Service
  infinity-rerank:
    image: michaelf34/infinity:latest
    container_name: infinity-rerank
    restart: always
    networks:
      - proxy
      - llm
    environment:
      - DATA_DIR=${DATA_DIR}
      - NVIDIA_VISIBLE_DEVICES=${RANKER_GPU}
      - INFINITY_MODEL_ID=${RAG_RERANK_MODEL}
      - INFINITY_LOG_LEVEL=info
    volumes:
      - ${DATA_DIR}/infinity:/app/.cache
    command: >
      v2
      --device cuda
      --engine torch
      --host 0.0.0.0
      --port 7991
      --url-prefix /v1
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
