services:
  pgvector:
    image: pgvector/pgvector:${PGVECTOR_TAG}
    container_name: pgvector
    networks:
      - proxy
      - llm
    volumes:
      - ${DATA_DIR}/postgres:/var/lib/postgresql/data
      - ${PROJ_DIR}/initdb.d:/docker-entrypoint-initdb.d
    environment:
      - DATA_DIR=${DATA_DIR}
      - PROJ_DIR=${PROJ_DIR}
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    command: postgres -c 'max_connections=200'
