services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    restart: unless-stopped
    container_name: plex
    ports:
      - "1901:1900/udp"
      - "3005:3005/tcp"
      - "8324:8324/tcp"
      - "32400:32400/tcp"
      - "32469:32469/tcp"
      - "32410:32410/udp"
      - "32412:32412/udp"
      - "32413:32413/udp"
      - "32414:32414/udp"
    networks:
      - proxy
      - plex
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - UMASK=${UMASK}
      - TZ=${PLEX_TZ}
      - DATA_DIR=${DATA_DIR}
      - FILE_DIR=${FILE_DIR}
      - ADVERTISE_IP=https://plex.${TRAEFIK_ACME_DOMAIN}
    volumes:
      - ${FILE_DIR}:/media
      - ${DATA_DIR}/plex/config:/config
      - ${DATA_DIR}/plex/transcode:/transcode
    labels:
      # Traefik integration
      - "traefik.enable=true"
      - "traefik.http.routers.plex.entrypoints=websecure"
      - "traefik.http.routers.plex.rule=Host(`plex.${TRAEFIK_ACME_DOMAIN}`)"
      - "traefik.http.routers.plex.tls.certresolver=cloudflare"
      - "traefik.http.services.plex.loadbalancer.server.port=32400"
      # Homepage integration
      - "homepage.group=Media"
      - "homepage.name=Plex"
      - "homepage.icon=plex.svg"
      - "homepage.href=https://plex.${TRAEFIK_ACME_DOMAIN}"
      - "homepage.description=Media Server"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
