services:
  pgvector:
    image: pgvector/pgvector:${PGVECTOR_TAG}
    container_name: db-pgvec
    userns_mode: host
    networks:
      - devel
      - genai
      - proxy
    volumes:
      - ${DATA_DIR}/postgres:/var/lib/postgresql/18/docker
      - ${PROJ_DIR}/initdb.d:/docker-entrypoint-initdb.d
    environment:
      - DATA_DIR=${DATA_DIR}
      - PROJ_DIR=${PROJ_DIR}
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    command: postgres -c 'max_connections=200'
    labels:
      # Traefik TCP for Postgres (LLM DB)
      - "traefik.enable=true"
      - "traefik.tcp.routers.pgvec.entrypoints=pgvec"
      - "traefik.tcp.routers.pgvec.rule=HostSNI(`pgvec.${TRAEFIK_ACME_DOMAIN}`)"
      - "traefik.tcp.routers.pgvec.service=pgvec"
      - "traefik.tcp.routers.pgvec.tls.certresolver=cloudflare"
      - "traefik.tcp.routers.pgvec.tls=true"
      - "traefik.tcp.services.pgvec.loadbalancer.server.port=5432"
