services:
  qdrant:
    image: qdrant/qdrant:${QDRANT_TAG}
    container_name: db-qdrant
    networks:
      - devel
      - genai
      - proxy
    ports:
      - ${QDRANT_HTTP_PORT}:${QDRANT_HTTP_PORT}
      - ${QDRANT_GRPC_PORT}:${QDRANT_GRPC_PORT}
    environment:
      QDRANT__SERVICE__HTTP_PORT: ${QDRANT_HTTP_PORT}
      QDRANT__SERVICE__GRPC_PORT: ${QDRANT_GRPC_PORT}
      QDRANT__GPU__INDEXING: 1
    volumes:
      - ${DATA_DIR}/qdrant:/qdrant/storage
    labels:
      # Traefik integration
      - "traefik.enable=true"
      - "traefik.http.routers.qdrant.entrypoints=websecure"
      - "traefik.http.routers.qdrant.rule=Host(`qdrant.${TRAEFIK_ACME_DOMAIN}`)"
      - "traefik.http.routers.qdrant.tls.certresolver=cloudflare"
      - "traefik.http.services.qdrant.loadbalancer.server.port=6333"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['${GPU_ID}']
              capabilities: [gpu]
