services:
  tei-embedder:
    image: ghcr.io/huggingface/text-embeddings-inference:86-latest
    container_name: tei-embed
    restart: "no"
    env_file:
      - ./hf.env
    environment:
      - MODEL_ID=${EMBEDDER_MODEL}
    networks:
      - genai
      - proxy
    ports:
      - 127.0.0.1:4000:4000
    volumes:
      - ${DATA_DIR}:/data
    secrets:
      - hf_token
    devices:
      - nvidia.com/gpu=${GPU_ID}
    deploy:
      resources:
        limits:
          memory: 12GB

  tei-reranker:
    image: ghcr.io/huggingface/text-embeddings-inference:86-latest
    container_name: tei-rerank
    restart: "no"
    env_file:
      - ./hf.env
    environment:
      - MODEL_ID=${RERANKER_MODEL}
    networks:
      - genai
      - proxy
    ports:
      - 127.0.0.1:4001:4000
    volumes:
      - ${DATA_DIR}:/data
    secrets:
      - hf_token
    devices:
      - nvidia.com/gpu=${GPU_ID}
    deploy:
      resources:
        limits:
          memory: 12GB

  tei-proxy:
    image: ghcr.io/delfianto/tei-proxy:latest
    container_name: tei-proxy
    restart: "no"
    env_file:
      - ./proxy.env
    networks:
      - genai
      - proxy
    ports:
      - 127.0.0.1:4002:4000
    deploy:
      resources:
        limits:
          memory: 128MB

networks:
  genai:
    external: true
  proxy:
    external: true

secrets:
  hf_token:
    file: ./secret/hf.secret
