services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    restart: "no"
    networks:
      - genai
      - proxy
    ports:
      - 127.0.0.1:11434:11434
    env_file:
      - ./ollama.env
      - ./main.env
    volumes:
      - ${DATA_DIR}:/root/.ollama
    healthcheck:
      test: ["CMD", "ollama", "list"]
      interval: 10s
      timeout: 5s
      retries: 5
    devices:
      - nvidia.com/gpu=0
      - nvidia.com/gpu=1
    deploy:
      resources:
        limits:
          memory: 24GB

  ollama-helper:
    image: ollama/ollama:latest
    container_name: ollama-smol
    restart: "no"
    networks:
      - genai
      - proxy
    ports:
      - 127.0.0.1:11435:11434
    env_file:
      - ./ollama.env
    environment:
      - OLLAMA_KEEP_ALIVE=-1
    volumes:
      - ${DATA_DIR}:/root/.ollama
    healthcheck:
      test: ["CMD", "ollama", "list"]
      interval: 10s
      timeout: 5s
      retries: 5
    devices:
      - nvidia.com/gpu=1
    deploy:
      resources:
        limits:
          memory: 2GB

  ollama-loader:
    image: ollama/ollama:latest
    container_name: ollama-loader
    restart: "no"
    networks:
      - genai
    depends_on:
      ollama-helper:
        condition: service_healthy
    volumes:
      - ./.env:/.env:ro
      - ./preload.sh:/preload.sh:ro
    entrypoint: ["/bin/bash", "/preload.sh", "--run"]
    deploy:
      resources:
        limits:
          memory: 100MB

networks:
  genai:
    external: true
  proxy:
    external: true
