services:
  pgvector:
    # Override the data directory volume mount for PostgreSQL on the host machine
    volumes:
      # Maps a host-specific directory to the container's PostgreSQL data path
      - /host-specific/postgres:/var/lib/postgresql/18/docker

  qdrant:
    # Modify deploy settings to reserve a specific NVIDIA GPU for Qdrant
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              # Override GPU device ID for GPU scheduling on this particular machine
              device_ids: ['0']

    # Modify Traefik-related labels to use a machine-specific domain name
    labels:
      # Enable Traefik routing for Qdrant service explicitly
      - "traefik.enable=true"
      # Define the entrypoint Traefik should listen on (websecure with TLS)
      - "traefik.http.routers.qdrant.entrypoints=websecure"
      # Override the rule to use a custom domain for this machine/environment
      - "traefik.http.routers.qdrant.rule=Host(`qdrant.custom-machine-domain.com`)"
      # TLS certificate resolver to use (Cloudflare in this example)
      - "traefik.http.routers.qdrant.tls.certresolver=cloudflare"
      # Define the backend service port Traefik should forward traffic to
      - "traefik.http.services.qdrant.loadbalancer.server.port=6333"
