services:
  valkey:
    image: valkey/valkey:9-alpine
    container_name: valkey
    restart: "no"
    command: valkey-server --save 60 1 --loglevel notice
    networks:
      - database
      - default
    ports:
      - 0.0.0.0:6379:6379
    volumes:
      - ${DATA_DIR}/valkey:/data
    healthcheck:
      test: ["CMD", "valkey-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          memory: 512MB

networks:
  database:
    external: true
