services:
  tugtainer:
    image: ghcr.io/quenary/tugtainer:1
    container_name: tugtainer
    restart: "no"
    networks:
      - proxy
    environment:
      - TZ=Asia/Jakarta
    volumes:
      - ${DATA_DIR}/tugtainer:/tugtainer
      - ${DOCKER_SOCK}:/var/run/docker.sock:ro
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.tugtainer.entrypoints=websecure"
      - "traefik.http.routers.tugtainer.rule=Host(`updates.${TRAEFIK_ACME_DOMAIN}`)"
      - "traefik.http.routers.tugtainer.tls.certresolver=cloudflare"
      - "traefik.http.services.tugtainer.loadbalancer.server.port=80"
      - "homepage.group=Core"
      - "homepage.name=Tugtainer"
      - "homepage.icon=docker.svg"
      - "homepage.href=https://updates.${TRAEFIK_ACME_DOMAIN}"
      - "homepage.description=Container Update Manager"
      - "dev.quenary.tugtainer.protected=true"
    deploy:
      resources:
        limits:
          memory: 512MB

networks:
  proxy:
    external: true
