services:
  portainer:
    image: portainer/portainer-ce:alpine-sts
    container_name: portainer
    restart: unless-stopped
    user: ${UID}:${GID}
    userns_mode: host
    networks:
      - proxy
    ports:
      - 9000:9000
    environment:
      # Group id should match with docker group id on host
      # otherwise Portainer won't be able to access Docker socket
      - UID=${UID}
      - GID=${GID}
      # Traefik domain name
      - TRAEFIK_ACME_DOMAIN=${TRAEFIK_ACME_DOMAIN}
    volumes:
      - ${DATA_DIR}/portainer:/data
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      # Traefik integration
      - "traefik.enable=true"
      - "traefik.http.routers.portainer.entrypoints=websecure"
      - "traefik.http.routers.portainer.rule=Host(`panel.${TRAEFIK_ACME_DOMAIN}`)"
      - "traefik.http.routers.portainer.tls.certresolver=cloudflare"
      - "traefik.http.services.portainer.loadbalancer.server.port=9000"
      # Homepage integration
      - "homepage.group=Core"
      - "homepage.name=Portainer"
      - "homepage.icon=portainer.svg"
      - "homepage.href=https://panel.${TRAEFIK_ACME_DOMAIN}"
      - "homepage.description=Container Management"
