services:
  postgres:
    image: tensorchord/vchord-suite:pg18-latest
    container_name: pgsql
    restart: "no"
    command: postgres -c "shared_preload_libraries=vchord" -c "max_connections=200"
    healthcheck:
      test: >-
        psql -U postgres -d postgres
        -c "SELECT 1 FROM pg_extension WHERE extname = 'vchord';"
        || exit 1
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_INITDB_ARGS: "--data-checksums"
    env_file:
      - ./postgres.env
    networks:
      - database
      - default
    ports:
      - 127.0.0.1:5432:5432
    secrets:
      - db_password
    volumes:
      - ${DATA_DIR}/postgres:/var/lib/postgresql/18/docker
    configs:
      - source: init-sql
        target: /docker-entrypoint-initdb.d/init.sql
    deploy:
      resources:
        limits:
          memory: ${MEM_LIMIT}

configs:
  init-sql:
    content: |
      CREATE EXTENSION IF NOT EXISTS vchord CASCADE;
      CREATE EXTENSION IF NOT EXISTS vchord_bm25 CASCADE;
      CREATE EXTENSION IF NOT EXISTS pg_tokenizer CASCADE;

networks:
  database:
    external: true

secrets:
  db_password:
    file: ${DATA_DIR}/postgres.txt
