services:
  stash:
    image: ghcr.io/feederbox826/stash-s6:hwaccel-develop
    restart: unless-stopped
    userns_mode: host
    networks:
      - proxy
      - stash
    logging:
      driver: json-file
      options:
        max-file: 10
        max-size: 2m
    environment:
      - PUID=${UID}
      - PGID=${GID}
      - STASH_CACHE=/cache
      - STASH_GENERATED=/generated
      - STASH_METADATA=/metadata
      - SKIP_NVIDIA_PATCH=true
      - STASH_PORT=9069
      - STASH_STASH=/media
      - MIGRATE=TRUE
    volumes:
      - ${LOCAL_TIME}:${LOCAL_TIME}:ro
      - ${DATA_DIR}/blobs:/blobs
      - ${DATA_DIR}/cache:/cache
      - ${DATA_DIR}/config:/root/.stash
      - ${DATA_DIR}/config_s6:/config
      - ${DATA_DIR}/generated:/generated
      - ${DATA_DIR}/metadata:/metadata
      - ${SRC1_DIR}:/media1
      - ${SRC2_DIR}:/media2
    labels:
      # Traefik integration
      - "traefik.enable=true"
      - "traefik.http.routers.stash.entrypoints=websecure"
      - "traefik.http.routers.stash.rule=Host(`stash.${TRAEFIK_ACME_DOMAIN}`)"
      - "traefik.http.routers.stash.tls.certresolver=cloudflare"
      - "traefik.http.services.stash.loadbalancer.server.port=9069"
      # Homepage integration
      - "homepage.group=Media"
      - "homepage.name=StashApp"
      - "homepage.icon=stash.svg"
      - "homepage.href=https://stash.${TRAEFIK_ACME_DOMAIN}"
      - "homepage.description=Media Server for Cultured Material"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
              count: all

networks:
  proxy:
    external: true
  stash:
    internal: true
